# Generated by Django 2.0.6 on 2018-06-27 06:52

from django.db import migrations, models
import thumb.fields.image_thumnail_field.model_field
import thumb.fields.video_thumbnail_field.model_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', thumb.fields.image_thumnail_field.model_field.ImageThumbnailField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('thumbnail', thumb.fields.video_thumbnail_field.model_field.VideoThumbnailField(upload_to='')),
            ],
        ),
    ]
